apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.0.244
    path: "/data/nfs/kubernetes/test"

