apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  selector:
    matchLabels:
      uygulama: web
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

