apiVersion: v1
kind: PersistentVolume
metadata:
  name: 172.16.0.244-pv1
  labels:
    uygulama: web
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.0.244
#    server: nfs-server.default.svc.cluster.local
    path: "/data/nfs/kubernetes/pvs/pv1"

