---
- name: Updating /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }} {{ item.fqdn }}"
    state: present
  with_items:
    - "{{ masters }}"
    - "{{ workers }}"

- name: Updating /etc/sysctl.d/k8s.conf file
  tags: sysctl_conf
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.bridge.bridge-nf-call-iptables = 1
  notify: reload sysctl

- name: Disable Swap 
  shell: swapoff -a

- name: Comment Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(.*swap*)'
    replace: '#\1'

