---
firewall_log_file: /var/log/firewalld-dropd.log

ports:
  - 6443/tcp
  - 2379-2380/tcp
  - 10250-10252/tcp
  - 10255/tcp
  - 6783/tcp
  - 6783-6784/udp
  - 8443/tcp

required_packages:
  - bash-completion
  - epel-release
  - https://download1.rpmfusion.org/free/el/updates/8/x86_64/r/rpmfusion-free-release-8-0.1.noarch.rpm
  - wget
  - git
  - nfs-utils
  - net-tools
  - tcpdump

