apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: centos
    image: centos:8
    env:
    - name: DB_USER 
      valueFrom:
        secretKeyRef:
          name: secret1
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret1
          key: DB_PASSWORD
    command:
      - sh
      - -c
      - 'while true; do echo $DB_USER, $DB_PASSWORD; sleep 180; done'
