apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-test
  template:
    metadata:
      labels:
        app: centos-test
    spec:
      containers:
      - name: centos
        image: centos:8
        command: ["sh","-c","while true; do echo $(date +%H:%M:%S) >> /mnt/data/test.txt; sleep 60; done"]
        volumeMounts:
        - mountPath: "/mnt/data"
          name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: lpvc
