apiVersion: v1
kind: Pod
metadata:
  name: dynamic-nfs-volume-pod
spec:  
  restartPolicy: Never
  containers:
  - name: centos
    image: "centos:8"
    command:
      - sh
      - -c
      - 'while true; do date > /tmp/dyn-nfs/index.html; hostname >> /tmp/dyn-nfs/index.html; sleep $(($RANDOM % 5 + 5)); done'
    volumeMounts:
      - mountPath: /tmp/dyn-nfs
        name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: dyn-nfs-pvc
