apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-file
spec:
  containers:
  - name: centos
    image: centos:8
    command:
      - sh
      - -c
      - 'while true; do cat /tmp/index.html; sleep 180; done'
    volumeMounts:
    - name: file
      mountPath: "/tmp/"
  volumes:
  - name: file
    configMap:
      name: file-cm
      items:
      - key: index.html 
        path: index.html

