apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  containers:
  - name: centos1
    image: centos:8
    command: ["sh", "-c", "while true; do echo $(hostname), $(date +%H:%M:%S) >> /output/test.txt; sleep 15; done"]
    volumeMounts:
    - name: my-volume
      mountPath: /output
  - name: centos2
    image: centos:8
    command: ['sh', '-c', 'while true; do cat /input/test.txt; sleep 15; done']
    volumeMounts:
    - name: my-volume
      mountPath: /input
  volumes:
  - name: my-volume
    emptyDir: {}
